- name: Deploy Docker Container
  hosts: web
  become: true

  tasks:
    - name: Pull latest Docker image
      docker_container:
        name: myapp
        image: dinesh7940/myapp:latest
        state: started
        recreate: true
        ports:
          - "80:8080"
